<?php

namespace TamoJuno;

class PicPay extends Resource {

    public function endpoint(): string
    {
        return 'qrcode';
    }

    public function createQRCode(array $form_params = [])
    {
        return $this->create($form_params);
    }

    public function post($id, array $form_params = [])
    {
        return parent::post($id, 'cancel', $form_params); // TODO: Change the autogenerated stub
    }
}